MxOnlineProject/urls.py
# _*_ encoding:utf-8 _*_
"""MxOnlineProject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
import xadmin

from users.views import LoginView, LogOutView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdForm
from users.views import IndexView
from organization.views import OrgView
from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url('^$', IndexView.as_view(), name='index'),
    url('^login/$', LoginView.as_view(), name='login'),
    url('^logout/$', LogOutView.as_view(), name='logout'),
    url('^register/$', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url('^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),
    url('^forget/$', ForgetPwdView.as_view(), name='forget_pwd'),
    url('^reset/(?P<active_code>.*)/$', ResetView.as_view(), name='reset_pwd'),
    url('^modify_pwd/$', ModifyPwdForm.as_view(), name='modify_pwd'),

    # 课程机构url配置
    url(r'^org/', include('organization.urls', namespace='org')),

    # 配置用户上传文件的访问处理
    url('^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # 配置静态文件的访问处理
    # url('^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),

    # 课程列表页url配置
    url(r'^courses/', include('courses.urls', namespace='courses')),

    # 个人中心url配置
    url(r'^users/', include('users.urls', namespace='users')),
    # ueditor
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

# 配置全局404页面
handler404 = 'users.views.page_not_found'

# 配置全局500页面
handler500 = 'users.views.server_error'

apps/courses/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

from courses.views import CourseListView, CourseDetailView, CourseInfoView, CourseCommentView,AddCommentView,VideoPlayView

urlpatterns = [
    # 课程列表页
    url('^list/$', CourseListView.as_view(), name='course_list'),
    # 课程详情页
    url('^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    # 课程章节页
    url('^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),
    # 课程评论页
    url('^comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name='course_comment'),
    # 对课程添加评论
    url('^add_comment/$', AddCommentView.as_view(), name='add_comment'),
    # 视频播放页面
    url('^video_play/(?P<video_id>\d+)$', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

from organization.views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, TeacherDetailView
from organization.views import OrgDescView, OrgTeacherView, AddFavView, TeacherListView

urlpatterns = [
    # 课程机构列表页
    url('^list/$', OrgView.as_view(), name='org_list'),
    # 用户咨询
    url('^add_ask/$', AddUserAskView.as_view(), name='add_ask'),
    # 机构首页
    url('^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='org_home'),
    # 机构课程列表页
    url('^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='course'),
    # 机构介绍
    url('^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='desc'),
    # 机构教师
    url('^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name='org_teacher'),
    # 机构收藏
    url('^add_fav/$', AddFavView.as_view(), name='add_fav'),

    # 课程讲师列表
    url('^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
    # 课程讲师详情
    url('^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail')
]

apps/users/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import UserInfoView, UploadImageView, UpdatePwdForm, SendEmailCodeView, UpdateEmailView
from .views import UserInfoView, MyCourseView, UserFavOrgView, UserFavTeacherView, UserFavCourseView,UserMessageView

urlpatterns = [
    # 课程机构列表页
    url('^info/$', UserInfoView.as_view(), name='user_info'),
    # 用户头像上传
    url('^image/upload/$', UploadImageView.as_view(), name='image_upload'),
    # 用户个人中心修改密码
    url('^update/pwd/$', UpdatePwdForm.as_view(), name='update_pwd'),
    # 修改邮箱发送验证码
    url('^send_code/$', SendEmailCodeView.as_view(), name='send_code'),
    # 修改邮箱
    url('^update_email/$', UpdateEmailView.as_view(), name='update_email'),
    # 我的课程
    url('^my_course/$', MyCourseView.as_view(), name='my_course'),
    # 课程机构收藏
    url('^fav_org/$', UserFavOrgView.as_view(), name='fav_org'),
    # 课程讲师收藏
    url('^fav_teacher/$', UserFavTeacherView.as_view(), name='fav_teacher'),
    # 课程课程收藏
    url('^fav_course/$', UserFavCourseView.as_view(), name='fav_course'),
    # 我的消息
    url('^message/$', UserMessageView.as_view(), name='message'),

]

apps/courses/models.py
# _*_ encoding:utf-8 _*_
from datetime import datetime

from django.db import models
from organization.models import CourseOrg, Teacher
from DjangoUeditor.models import UEditorField


# Create your models here.

class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name=u'课程机构', null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name=u'课程名')
    desc = models.CharField(max_length=300, verbose_name=u'课程描述')
    detail = UEditorField(verbose_name=u'课程详情', width=600, height=300, imagePath="course/ueditor/image/",
                          filePath="course/ueditor/file/", default='')
    is_banner = models.BooleanField(default=False, verbose_name=u'是否轮播')
    degree = models.CharField(max_length=5, verbose_name=u'课程难度', choices=(('cj', '初级'), ('zj', '中级'), ('gj', '高级')))
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长(分)')
    students = models.IntegerField(default=0, verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name=u'收藏人数')
    image = models.ImageField(upload_to='course/%Y/%m', verbose_name=u'封面图')
    click_nums = models.IntegerField(default=0, verbose_name=u'点击数')
    category = models.CharField(default='后端开发', max_length=20, verbose_name=u'课程类别')
    tag = models.CharField(default='', max_length=10, verbose_name=u'课程标签')
    teacher = models.ForeignKey(Teacher, verbose_name=u'课程讲师', null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_zj_nums(self):
        # 获取课程章节数
        return self.lesson_set.all().count()

    # 设置后台显示的标签title
    get_zj_nums.short_description = u'章节数'

    # 后天添加跳转
    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe('<a href="http://127.0.0.1:8000/courses/detail/{}/">跳转<a/>'.format(self.id))

    def get_learn_user(self):
        # 获取学习用户
        return self.usercourse_set.all()[:5]

    def get_zj(self):
        # 获取课程所有章节
        return self.lesson_set.all()


# 把课程中是轮播课程的单独展示
class BannerCourse(Course):
    class Meta:
        verbose_name = u'轮播课程'
        verbose_name_plural = verbose_name
        proxy = True


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_video(self):
        # 根据章节获取video
        return self.video_set.all()


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u'章节')
    name = models.CharField(max_length=100, verbose_name=u'名称')
    url = models.CharField(max_length=100, default='', verbose_name=u'视频地址')
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长(分)')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'名称')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name=u'资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/base.html
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %} - 慕学在线网{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                    <!--登录后跳转-->
                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>bobby<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.image }}"/>
                                    </dt>
                                    <dd>
                                        <h2>{{ user.nick_name }}</h2>
                                        <p>{{ user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
                    <a href="{% url 'users:message' %}">
                        <div class="msg-num"><span id="MsgNum">{{ user.unread_num }}</span></div>
                    </a>

                </div>
            </div>
            <div class="middle">
                    <div class="wp">
                        <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                        <div class="searchbox fr">
                            <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                                <ul class="selectMenu" id="jsSelectMenu">
                                    <li data-value="course">公开课</li>
                                    <li data-value="org">课程机构</li>
                                    <li data-value="teacher">授课老师</li>
                                </ul>
                            </div>
                            <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                            <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                        </div>
                    </div>
                </div>

                <nav>
                    <div class="nav">
                        <div class="wp">
                            <ul>
                                <li {% if request.path == '/' %} class="active" {% endif %}><a href="{% url 'index' %}">首页</a></li>
                                <li {% if request.path|slice:'8' == '/courses' %} class="active" {% endif %}>
                                    <a href="{% url 'courses:course_list' %}">公开课<img class="hot" src="{% static 'images/nav_hot.png' %}"></a>
                                </li>
                                <li {% if request.path|slice:'12' == '/org/teacher' %} class="active" {% endif %}>
                                    <a href="{% url 'org:teacher_list' %}">授课教师</a>
                                </li>
                                <li {% if request.path|slice:'9' == '/org/list' %} class="active" {% endif %}>
                                    <a href="{% url 'org:org_list' %}">授课机构</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>

        </div>
    </header>
</section>
<!--crumbs start-->

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}

{% endblock %}

<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
                <li class="code"><img src="{% static 'images/code.jpg' %}"/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
                    <p class="tell">33333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>

{% block custom_js %}

{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}首页-慕学在线网{% endblock %}

{% block custom_bread %}
{% endblock %}

{% block content %}
    <div class="banner">
        <div class="wp">
            <div class="fl">
                <div class="imgslide">
                    <ul class="imgs">
                        {% for banner in all_banner %}
                            <li>
                                <a href="{{ banner.url }}">
                                    <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}"/>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>

        </div>


    </div>
    <!--banner end-->
    <!--feature start-->
    <section>
        <div class="wp">
            <ul class="feature">
                <li class="feature1">
                    <img class="pic" src="{% static 'images/feature1.png' %}"/>
                    <p class="center">专业权威</p>
                </li>
                <li class="feature2">
                    <img class="pic" src="{% static 'images/feature2.png' %}"/>
                    <p class="center">课程最新</p>
                </li>
                <li class="feature3">
                    <img class="pic" src="{% static 'images/feature3.png' %}"/>
                    <p class="center">名师授课</p>
                </li>
                <li class="feature4">
                    <img class="pic" src="{% static 'images/feature4.png' %}"/>
                    <p class="center">数据真实</p>
                </li>
            </ul>
        </div>
    </section>
    <!--feature end-->
    <!--module1 start-->
    <section>
        <div class="module">
            <div class="wp">
                <h1>公开课程</h1>
                <div class="module1 eachmod">
                    <div class="module1_1 left">
                        <img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
                        <p class="fisrt_word">名师授课<br/>专业权威</p>
                        <a class="more" href="{% url 'courses:course_list' %}">查看更多课程 ></a>
                    </div>
                    <div class="right group_list">
                        <div class="module1_2 box">
                            <div class="imgslide2">
                                <ul class="imgs">
                                    {% for course in banner_courses %}
                                        <li>
                                            <a href="{% url 'courses:course_detail' course.id %}">
                                                <img width="470" height="300"
                                                     src="{{ MEDIA_URL }}{{ course.image }}"/>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="unslider-arrow2 prev"></div>
                            <div class="unslider-arrow2 next"></div>
                        </div>
                        {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:course_detail' course.id %}">
                                        <h2 title="django入门">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="慕课网">{{ course.course_org }}</span>
                                    <span class="star fr">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="module greybg">
            <div class="wp">
                <h1>课程机构</h1>
                <div class="module3 eachmod">
                    <div class="module3_1 left">
                        <img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
                        <p class="fisrt_word">名校来袭<br/>权威认证</p>
                        <a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
                    </div>
                    <div class="right">
                        <ul>
                            {% for org in orgs %}
                                <li {% if forloop.counter|divisibleby:5 %}class="five" {% endif %}>
                                    <a href="{% url 'org:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="慕课网">{{ org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/password_reset.html
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>密码修改</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'modify_pwd' %}" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <input type="hidden" value="{{ email }}" name="email">
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <div class="error btns" id="jsForgetTips">{% for key,error in forget_form.errors.items %}{{ error }}{% endfor %}{{ msg }}</div>
                <li class="button">
                    <input type="submit" value="提交" onclick="reset_password_form_submit()">
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="{% static 'images/check2.png' %}">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter_base.html' %}
{% load staticfiles %}
{% block title %}个人信息{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block custom_right %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li><a href="{% url 'users:fav_org' %}">课程机构</a></li>
                    <li><a href="{% url 'users:fav_teacher' %}">授课教师 </a></li>
                    <li class="active"><a href="{% url 'users:fav_course' %}">公开课程</a></li>
                </ul>

            </div>
            <div class="companycenter">
                <div class="group_list brief">
                    {% for course in all_courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter_base.html' %}
{% load staticfiles %}
{% block title %}个人信息{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block custom_right %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>

        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="{% url 'users:fav_org' %}">课程机构</a></li>
                    <li><a href="{% url 'users:fav_teacher' %}">授课教师 </a></li>
                    <li><a href="{% url 'users:fav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="messagelist">
                {% for org in all_orgs %}
                    <div class="messages butler_list company company-fav-box">
                    <dl class="des fr">
                        <dt>
                            <a href="{% url 'org:org_home' org.id %}">
                                <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                            </a>
                        </dt>
                        <dd>
                            <h1><a href="{% url 'org:org_home' org.id %}">{{ org.name }}</a></h1>
                            <div class="pic fl" style="width:auto;">

                                <img src="{% static 'images/authentication.png' %}"/>


                                <img src="{% static 'images/gold.png' %}"/>

                            </div>
                            <span class="c8 clear">{{ org.address }}</span>
                            <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                        </dd>
                    </dl>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/usercenter-mycourse.html
{% extends 'usercenter_base.html' %}
{% load staticfiles %}
{% block title %}个人信息{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>个人信息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block custom_right %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的课程</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="companycenter">
                <div class="group_list brief">
                    {% for course in all_courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail' course.course.id %}">
                                <img width="214" height="190" class="scrollLoading"
                                     src="{{ MEDIA_URL }}{{ course.course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:course_detail' course.id %}"><h2>{{ course.course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ course.course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course.course_org.name }}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ course.course.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}